already_augmented: false
detection_conf: 0.6
detection_im_size: 416
batch_size: 64
epochs: 100
feat_vec_path: None
img_size_test: 640
img_size_tr: 640
names: None
nc: 0
test: None
train: None
val: None
weight_file_path: None
wfile_path_freezing_layer: None
retrain_im_th: 500 # threshold that the folder of images needs to overcome in order to be added in the train
temp_tr_data_path: None # path to images temp stored, waiting to reach retrain_im_th to be put in the training set